### PR TITLE
Fix flake so latest ironhide works on mac

### PR DESCRIPTION
**Pull request by zmre**
Was getting an error about a missing dependency when upgrading from 1.0.5 to latest. This fixes the problem.

### CODE REVIEW

**Comment by zmre** [comment]
No idea whey the checks were cancelled. It says, `Error: The operation was canceled.` But I didn't cancel it...

Side note: when this gets accepted, can we bump the version to 1.0.8 even though it's only a flake change?  I'm not sure the right way to do that, but it will help for upgrading to a working version in my nix config.

**Comment by zmre** [comment]
Gah, the checks are failing because:

```
error[E0282]: type annotations needed for `Box<_>`
  = note: this is an inference error on crate `time` caused by an API change in Rust 1.80.0; update `time` to version `>=0.3.35` by calling `cargo update`
error: could not compile `time` (lib) due to 1 previous error
```

So looks like we need to upgrade at least the time library. I will attempt that.

**Review by BobWall23 — APPROVED** [review]
